apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.jenkins: |
    url: "http://192.168.101.41:8081/job/hello-world/build?token=demoapp"
    basicAuth:
      username: $jenkins-username
      password: $jenkins-password

