apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.jenkins: |
    url: "http://192.168.101.41:8081/job/hello-world/build?token=demoapp"
    basicAuth:
      username: $jenkins-username
      password: $jenkins-password

  template.jenkins-params: |
    webhook:
      jenkins:
        method: GET
        body: name=Bhavesh&message="Hello World!!!"

  trigger.on-deployed: |
    - description: Application is synced and healthy. Triggered once per commit.
      oncePer: app.status.sync.revision
      send:
      - jenkins-params
      when: app.status.operationState.phase in ['Succeeded'] and app.status.health.status == 'Healthy'
